### PR TITLE
port to python 3.5

### PR DESCRIPTION
**Pull request by rpuntaie**
Hello nvie. I've ported this little vim plugin to python 3.5 enabled VIM. It still should work with VIM with Python 2.7 as well, but I haven't tried. It would be great if you could take over these changes.

### CODE REVIEW

**Comment by wdoekes** [comment]
@rpuntaie, at the risk of having duplicating your work, I've also ported it to py3 only:
https://github.com/ossobv/vim-rst-tables-py3

**Comment by timcera** [comment]
Any hope to get this moving forward?

**Comment by rpuntaie** [comment]
@wdoekes, I've just seen, you've added support for ``|replacements|``. I'll use, yours then.

**Comment by rpuntaie** [comment]
This seems not to be maintained any more. @wdoekes, maybe you could also integrate https://github.com/nvie/vim-rst-tables/pull/26.

**Pull request closed without merging**
